### ISSUE TITLE
SEDE Fetching API / Wrapper using direct-to-CSV result links

### ISSUE THREAD

**Issue by magisch** [SOBotics/Nursery#11]
On direct request here: https://chat.stackoverflow.com/transcript/message/45586747#45586747 and based on the SOBotics Team Post here: https://stackoverflow.com/c/sobotics/questions/344 I'm proposing a bot that helps with the detection and reviewing of suspect serial voting. The most expedient way to collect data on this (because a working implementation of the algorhitm to detect suspect voting patterns already exists - see the team post) is via the Stack Exchange Data Explorer (SEDE). To turn this into a bot, an automated way of regularly fetching data from SEDE is necessary. In addition, other projects could benefit from having an easy-to-access API or Wrapper available for their own purposes. 

It's already possible to directly obtain a CSV version of the query results as download, for any given query. Parameters in the query itself can be specified in the URI. An example would be: https://data.stackexchange.com/interpersonal/csv/1061535, which returns a CSV file of the results.

**Comment by rschrieken** [comment]
Might be of use: https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/tree/master/source/SOCVR.Chatbot/Sede

**Comment by jdd-software** [comment]
[SEDEApi](https://github.com/SOBotics/SEDEApi), the lambda is already in production, URL and access token needs to be request by SOBotics. It can also be used as a library to access SEDE.
