### ISSUE TITLE
Tag wiki edits needing review

### ISSUE THREAD

**Issue by kingboyk** [SOBotics/Nursery#2]
I like to review tag wiki edits as I have noticed how slow the review process can be for such edits.

It would be really helpful if I could interact with a bot - maybe Jammy? - to get a list of tag wiki edits needing review.

**Comment by Bhargav-Rao** [comment]
This is going to be hard. Tag wikis or edit suggestions on tag wikis [are not available on the API.][2] [Tag Wiki Edit Monitor][1] tries to hack a way through by predicting them, by looking at those reviews which aren't available in the API. 

If you want to get these tag wiki edits after a while, that'd be very difficult, as many of the suggested edits which are approved/rejected would also not be available as "reviews" in the API, and hence trying the same hack as TWEM would not be very helpful here. 

One quick way for a human would be to check Jammy's reports, via the /search page. I'm not sure about how to implement it for a bot. I am all ears if anyone has any idea. 

  [1]: https://github.com/SOBotics/TagWiki-Monitor
  [2]: https://stackapps.com/questions/3169/why-doesnt-the-api-return-suggested-edits-on-tag-wikis

**Comment by kingboyk** [comment]
Personally I'm not so interested in this any more, and Bhargav said it would be hard, so I'll close the issue for now.

**Comment by Bhargav-Rao** [comment]
@kingboyk Oh no, there was no need to close this. My plan was to link Tag Wiki monitor to Higgs, so that y'all could review it. But there's just too much on the backlog, which is why I hadn't commented on this yet. Sorry that it took really long.

**Comment by kingboyk** [comment]
It's not that I got tired of waiting @Bhargav-Rao , I'm just not so interested in reviewing tag wikis at the moment. If you're planning to do something regardless and want to use this issue to track it, then of course reopen it :)

SK
