### ISSUE TITLE
SoundFlow - making large pings in rooms easier

### ISSUE THREAD

**Issue by double-fault** [SOBotics/Nursery#5]
**Name of the bot:** SoundFlow
**General topic:** Chatroom pings 
**Problem, the bot is supposed to solve:**  

In rare cases when we have to ping a number of users, say all the ROs, or the developers of a bot (where a number of people are collaborating), we need to think to remember all names, or check out the bot's page to see all its developers; instead of this, with SoundFlow, just write something like `@Team/BotName`, and all devs of that bot will be pinged. 

**Ideas for implementation:**

Preferably, all the teams should be stored in a file on GH; commands manipulating them will just add unnecessary complexity, which is not needs as teams don't change everyday. A privilege system should be important, especially for some teams like all ROs.  

The bot will need to listen to two different name, `@SoundFlow`, and `@Team/blah`. Some basic commands like `stop`, `reboot` etc. will be useful. Redunda integration is also a very useful step IMHO.

Once the `@Team/blah` has been used, the bot should recognise the team, and post a message pinging all the users.

---

Pinging has been a very controversial idea in the past, especially mass pings. If anyone has objections, please post a comment.

**Comment by Filnor** [comment]
You mentioned a privilege system. I think that should be used to prevent abuse (because mass pings would be a perfect bait for trolls and such).

**Comment by Bhargav-Rao** [comment]
Perhaps restrict pings to Room Owners/Moderators, but have the name display to everyone?

**Comment by double-fault** [comment]
@pbdevch @Bhargav-Rao I do agree that a privilege system is extremely important. Maybe allow all ROs/mods, and a specific set of users who are regulars in the room? I also like the idea to have the names display to everyone.

**Comment by Bhargav-Rao** [comment]
This would be a good addition. Anybody has any thoughts on developing it?

**Comment by Filnor** [comment]
I would throw in myself for developing it, but I have some objections and questions before I could start:

## Account
Done.  
~I think it's good idea to create a new bot account (called `SoundFlow`), but for development, I could use CheckYerFlags' account for the start.  
*Maybe a mod/RO wants to help out doing the required edits for the bot account?*~
## User storing
Done.
~The easiest way to ping the users would be by storing their name plaintext in the file, something along:~
```
"users": [
    "Filnor",
    "CheckYerFlags"
]
```
~But that would raise problems if a user changes their display name, so I think it would be better to store the user ID's and then fetch the display name/pingeable name using the chat lib.~

## Initial team/bot list
Done.
~For the start and testing, it would be nice to have a list of teams and users.~

## Privilege system/trusted regulars
Done. Created a list with users I'm very confident to be trustworthy.
~As previously discussed here, the access to the bot should be restricted to ROs, moderators and a specific set of regulars in the room. Who exactly would that regulars be?~

## Other things
- I would propose Thunder integration alongside Redunda, as Thunder wasn't a thing back when this was created (IIRC)
- I know Python for bot programming ([CheckYerFlags](https://github.com/SOBotics/FlaggersHall) and [ChatCradle](https://github.com/Filnor/ChatCradle)) and would go with that again, if that's OK.

**Comment by double-fault** [comment]
What do you mean by thunder integration? 

I have a slightly different method of implementation, but I’m very busy right now, sorry. Thanks @Filnor for taking the responsibility to develop this!

**Comment by Filnor** [comment]
@Fortunate-MAN By Thunder intergration I just mean we add the bot to
Thunder, like we do with most others.



Am Di., 3. Juli 2018 um 14:10 Uhr schrieb Fortunate-MAN <
notifications@github.com>:

**Comment by Filnor** [comment]
Please redirect any further discussions & comments as [issues in the SoundFlow repository](https://github.com/SOBotics/SoundFlow/issues), so we can close this issue here.
