### ISSUE TITLE
Move HeatDetector to api

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Nursery#6]
**Name of the bot:** HeatDetector
**General topic:** Classify comments
**Requires feedback:** No, it's an api that other bots can call and then integrate with Higgs to handle feedback
**Problem, the bot is supposed to solve:**  
I want to move the classifying code to an api, the main reasons are:

1. Other bots can easily use HeatDetectors classifying code, hence its easy for someone to setup a bot for another SE site or for SE Chat.
2. Possibility to handle regex's from web interface.
3. Possibility to handle feeds from web interface.
4. Possibility to test from web interface.
5. Better code structure (it's currently hidden in SOCVFinders, duplicate thread)

**Ideas for implementation:**
As a first step I will develop a spring-boot with all the services, if I still have energy or someone else like to join in we can add a web interface in angular to address point 2,3 and 4

**Comment by Bhargav-Rao** [comment]
The work on this has started and further issues can be added on the actual repository. https://github.com/SOBotics/HeatDetector
