### ISSUE TITLE
BurniDator - Collecting data for burnination requests

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Nursery#8]
**Name of the bot:** BurniDator
**General topic:** Collecting data for burnination requests
**Requires feedback:** no
**Problem, the bot is supposed to solve:**  Lots of manual work, and no updates to the Burnination worksheet in the Trogdor room

**Ideas for implementation:**

The [Trogdor chat room](https://chat.stackoverflow.com/rooms/165597/trogdor) has been involved in getting the burnination queue down as much as possible. The room members have created a nice [worksheet](https://docs.google.com/spreadsheets/d/1zNR84e7Is2j7XBkCI277KYjnxWxQhjMKq6p0U-awEW0/edit?usp=sharing) where data about every burnination request is stored clearly. The issue is that it is very tedious to update, and involves a lot of manual work, which could otherwise be clearly handled. 

We can start by collecting the data from that spreadsheet, converting it into bot readable format, then analyze each of them. We need to update the status tags for each of those. We would need to check in each and every new burnination request and store data about that. 

The additional requirements of the bot would be:

- a manual way to edit the information available in the system.
- a way to periodically update the information stored. 
- a way to download/export the entire dataset.

**Comment by rjrudman** [comment]
We might be able to leverage Higgs to do this (with or without a bot).

Here's an example 'report' I manually added:

https://higgs.sobotics.org/Burny%20Taggerrs/report/4301

![image](https://user-images.githubusercontent.com/709585/43118418-1cdad672-8f55-11e8-841a-dbea278a3354.png)

Currently, Higgs doesn't allow reports to be edited. That's [raised as an issue already](https://github.com/SOBotics/Higgs/issues/15).

In addition, currently only 'bot' users are able to create reports. That's something we'll need to modify as well. Regardless, what do people think of storing information in this format?

A userscript could be created to parse a meta post, and push/update the information on Higgs

**Comment by Bhargav-Rao** [comment]
Implemented as Rodgort.  https://github.com/SOBotics/Rodgort
