### ISSUE TITLE
Checking recreation of burned tags.

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Nursery#9]
**Name of the bot:**  - 
**General topic:** tags
**Requires feedback:** no
**Problem, the bot is supposed to solve:**  

Check which all tags are recreated after burnination. The list of burned tags are available here https://github.com/SOBotics/Tagdor/blob/master/StatusCompletedBurninateRequests.csv. 

**Ideas for implementation:**

Should read that CSV and get the list of burned tags. Then call `/tags/{tags}/info` API (5 calls maximum) every 7 days, and post any match to chat.

**Comment by Bhargav-Rao** [comment]
Name Proposal (@adeak): Revenant

**Comment by Bhargav-Rao** [comment]
Name Proposal (me): Phoenix

**Comment by g00glen00b** [comment]
Name Proposal: Tagminator

Reason: It's a wordplay on "Tag" and "Terminator".
Additional idea: Each time a tag is burnt again, the chatbot should say:

```
Hasta la vista, [tag:tagname]
```

**Comment by superplane39** [comment]
Name Proposal: Zombie Watcher

**Comment by NobodyNada** [comment]
FWIW, FireAlarm could do this pretty easily — although it may be desirable to separate it into another bot.

FA currently has a tag blacklist, designed for bad-question-magnets like [seo].  If a question is posted in a blacklisted tag, the question is guaranteed to be reported.  I could trivially create another blacklist for burninated tags, or I could make a new FireAlarm-based bot for that purpose.

I’m currently working full-time so I don’t have much spare time to work on this, but it shouldn’t take more than an hour so I can hopefully fit it in somewhere.

**Comment by Bhargav-Rao** [comment]
@NobodyNada, https://github.com/sobotics/tagdor provides an API where you can look up if a tag is burninated before or not. Perhaps FA can query that for all the 5 tags of a question?

**Comment by NobodyNada** [comment]
@Bhargav-Rao It’d probably be easier if FA just downloaded and parsed the CSV on startup, rather than making 5 HTTP requests per question.

**Comment by Bhargav-Rao** [comment]
I'm surprised that the blacklisted tag isn't being used widely. https://chat.stackoverflow.com/search?q=blacklisted+tag&user=6373379  Is there a way to blacklist a tag? (I don't see it here https://github.com/SOBotics/FireAlarm/wiki/CommandsSwift)

**Comment by NobodyNada** [comment]
Sorry it’s not in the commands list, I don’t do a great job of keeping that up to date.  IIRC the commands are `blacklist tag name`, `unblacklist tag name`, and `blacklisted tags`.

**Comment by double-fault** [comment]
Here's the channels discussion for those who haven't seen it: https://stackoverflow.com/c/sobotics/questions/290

**Comment by Bhargav-Rao** [comment]
The work on this has started and further issues can be added on the actual repository. https://github.com/SOBotics/Revenant
